import type { Core } from '@strapi/strapi';

/**
 * Editorial roles for the admin panel, built from the page prefix in every
 * content type's display name ("Alumni – Chapters" belongs to the "Alumni"
 * group). Strapi checks permissions per content type, so this prefix is what
 * lets one role cover "everything on the Alumni page and its subpages".
 *
 * Runs on every boot but only CREATES roles that don't exist yet — anything a
 * Super Admin later changes in Settings → Administration Panel → Roles is
 * never overwritten. To rebuild these roles from scratch (e.g. after adding
 * new content types), start Strapi once with SYNC_ADMIN_ROLES=true.
 */

const CM = 'plugin::content-manager.explorer';
const ACTIONS = {
  create: `${CM}.create`,
  read: `${CM}.read`,
  update: `${CM}.update`,
  delete: `${CM}.delete`,
  publish: `${CM}.publish`,
};

const MEDIA_EDIT = [
  'plugin::upload.read',
  'plugin::upload.assets.create',
  'plugin::upload.assets.update',
  'plugin::upload.assets.download',
  'plugin::upload.assets.copy-link',
];

const groupOf = (displayName: string) => displayName.split(/\s[–-]\s/)[0].trim();
const slug = (s: string) => s.toLowerCase().replace(/&/g, 'and').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

export async function ensureAdminRoles({ strapi }: { strapi: Core.Strapi }) {
  const roleService: any = strapi.service('admin::role');
  const force = process.env.SYNC_ADMIN_ROLES === 'true';

  // Every API content type, grouped by its page prefix.
  const types = Object.values(strapi.contentTypes as Record<string, any>).filter((ct) => ct.uid.startsWith('api::'));
  const groups = new Map<string, any[]>();
  for (const ct of types) {
    const g = groupOf(ct.info?.displayName ?? ct.uid);
    groups.set(g, [...(groups.get(g) ?? []), ct]);
  }

  // Full permission objects (with nested component fields) for every
  // content-manager action, generated by Strapi itself so they match exactly
  // what the Roles screen would produce.
  const actionProvider = (strapi.service('admin::permission') as any).actionProvider;
  const cmActions = actionProvider.values().filter((a: any) => String(a.actionId).startsWith(`${CM}.`));
  const allPerms: any[] = (strapi.service('admin::content-type') as any).getPermissionsWithNestedFields(cmActions);

  const forTypes = (uids: Set<string>, actions: string[]) =>
    allPerms
      .filter((p) => uids.has(p.subject) && actions.includes(p.action))
      .map((p) => ({ ...p, conditions: [] }));

  const media = (actions: string[]) =>
    actions.map((action) => ({ action, subject: null, properties: {}, conditions: [] }));

  // Types another group's content points at (e.g. news -> unit) get read-only
  // access, otherwise the relation picker would be empty for that editor.
  const relationTargets = (list: any[]): Set<string> => {
    const own = new Set(list.map((c) => c.uid));
    const out = new Set<string>();
    for (const ct of list) {
      for (const attr of Object.values<any>(ct.attributes)) {
        if (attr.type === 'relation' && attr.target?.startsWith('api::') && !own.has(attr.target)) out.add(attr.target);
      }
    }
    return out;
  };

  const allUids = new Set(types.map((t) => t.uid));

  const definitions: { code: string; name: string; description: string; permissions: () => any[] }[] = [
    {
      code: 'website-manager',
      name: 'Website Manager',
      description: 'Edits and publishes every page. Cannot manage users, roles or settings.',
      permissions: () => [
        ...forTypes(allUids, [ACTIONS.create, ACTIONS.read, ACTIONS.update, ACTIONS.delete, ACTIONS.publish]),
        ...media(MEDIA_EDIT),
      ],
    },
    {
      code: 'content-author-draft-only',
      name: 'Content Author (Draft Only)',
      description: 'Can create and edit any content but cannot delete or publish. A senior editor publishes.',
      permissions: () => [...forTypes(allUids, [ACTIONS.create, ACTIONS.read, ACTIONS.update]), ...media(MEDIA_EDIT)],
    },
    {
      code: 'viewer',
      name: 'Viewer',
      description: 'Read-only access to all content.',
      permissions: () => [...forTypes(allUids, [ACTIONS.read]), ...media(['plugin::upload.read'])],
    },
    ...[...groups.entries()]
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([group, list]) => ({
        code: `${slug(group)}-editor`,
        name: `${group} Editor`,
        description: `Edits and publishes only the ${group} pages and their subpages.`,
        permissions: () => {
          const own = new Set<string>(list.map((c) => c.uid));
          return [
            ...forTypes(own, [ACTIONS.create, ACTIONS.read, ACTIONS.update, ACTIONS.delete, ACTIONS.publish]),
            ...forTypes(relationTargets(list), [ACTIONS.read]),
            ...media(MEDIA_EDIT),
          ];
        },
      })),
  ];

  for (const def of definitions) {
    let role = await roleService.findOne({ code: def.code });
    if (role && !force) continue;
    if (!role) role = await roleService.create({ name: def.name, code: def.code, description: def.description });
    await roleService.assignPermissions(role.id, def.permissions());
    strapi.log.info(`[admin-roles] ${force ? 'synced' : 'created'} role "${def.name}"`);
  }

  // Drop auto-created "<Group> Editor" roles for page groups that no longer
  // exist (e.g. after a content type is removed) — only when nobody uses them.
  const wanted = new Set(definitions.map((d) => d.code));
  const existing: any[] = await roleService.findAllWithUsersCount({});
  for (const r of existing) {
    const isStale = /-editor$/.test(r.code) && r.code !== 'strapi-editor' && !wanted.has(r.code);
    if (isStale && r.usersCount === 0) {
      await roleService.deleteByIds([r.id]);
      strapi.log.info(`[admin-roles] removed unused role "${r.name}"`);
    }
  }
}
